#pragma once

void test_string_create_returns_empty_string_when_given_null(void);

void test_string_create_returns_string_with_correct_length_and_data(void);

void test_string_create_does_not_modify_original_string(void);

void test_string_emptry_returns_emptry_string(void);

void test_string_to_c_string_returns_empty_string_if_string_is_null(void);

void test_string_to_c_string_returns_empty_string_if_string_data_is_null(void);

void test_string_to_c_string_returns_correct_c_string(void);
